name: Build and Test React application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [24.x, 25.x]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node_version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node_version}}
      - name: pnpm ci, build and test
        run: |
          pnpm ci
          pnpm run build --if-present
          pnpm test
